import './styles.css';

const bridge={
  available:()=>Boolean(window.go?.main?.App),
  call(name,...args){const fn=window.go?.main?.App?.[name];return fn?fn(...args):Promise.reject(new Error('Wails bridge unavailable'));}
};
const fallback={
  core:{running:true,managed:true,address:'http://127.0.0.1:18765',state:'running'},
  connections:[{name:'internal',kind:'internal',description:'Core 所在本机'},{name:'dev-server',kind:'remote',host:'dev.example.test',user:'developer',port:22},{name:'staging',kind:'remote',host:'staging.example.test',user:'operator',port:22}],
  sessions:[{id:'session-demo-01',name:'API 开发',status:'running',mode:'pty',ssh_endpoint:'remote',shells:[{id:'shell-demo-01',name:'build',status:'running',mode:'pty'},{id:'shell-demo-02',name:'logs',status:'running',mode:'pty'}]},{id:'session-demo-02',name:'本地工作区',status:'running',mode:'pty',ssh_endpoint:'internal',shells:[{id:'shell-demo-03',name:'zsh',status:'running',mode:'pty'}]}],
  history:[{id:'history-demo-01',name:'发布检查',status:'archived',reason:'explicit',ssh_endpoint:'remote',tags:['release']}],forwards:[],fetched_at:new Date().toISOString(),preview:true
};
const state={data:fallback,loading:true,error:'',section:'resources',filter:'',selected:{type:'core',id:'core'},expanded:new Set(['connection:internal','connection:dev-server','connection:staging']),dialog:null};
const icons={resources:'<path d="M4 5h6l2 2h8v12H4z"/><path d="M4 9h16"/>',sessions:'<rect x="4" y="5" width="16" height="14" rx="2"/><path d="m8 10 2 2-2 2m5 0h3"/>',history:'<circle cx="12" cy="12" r="8"/><path d="M12 8v5l3 2M4 5v4h4"/>',terminal:'<path d="m5 7 4 5-4 5m7 0h7"/>',core:'<path d="M8 3h8v4h4v10h-4v4H8v-4H4V7h4z"/><circle cx="12" cy="12" r="3"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M12 3v3m0 12v3M3 12h3m12 0h3m-2.6-6.4-2.1 2.1M7.7 16.3l-2.1 2.1m12.8 0-2.1-2.1M7.7 7.7 5.6 5.6"/>',refresh:'<path d="M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 12-2l2 2M18 17a7 7 0 0 1-12 2l-2-2"/>',plus:'<path d="M12 5v14M5 12h14"/>',search:'<circle cx="11" cy="11" r="6"/><path d="m16 16 4 4"/>',chevron:'<path d="m9 6 6 6-6 6"/>'};
const icon=(n,s=17)=>`<svg viewBox="0 0 24 24" width="${s}" height="${s}" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[n]||''}</svg>`;
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const dot=(s='running')=>`<i class="status-dot ${s}"></i>`;
const shellCount=()=>state.data.sessions.reduce((n,s)=>n+(s.shells?.filter(x=>x.status==='running').length||0),0);
const match=(v,q)=>!q||String(v).toLowerCase().includes(q);

async function refresh(){state.loading=true;state.error='';render();try{state.data=bridge.available()?await bridge.call('GetSnapshot'):{...fallback,preview:true};}catch(e){state.error=String(e);}finally{state.loading=false;render();}}
function selected(){const {type,id}=state.selected;if(type==='connection')return state.data.connections.find(x=>x.name===id);if(type==='session')return state.data.sessions.find(x=>x.id===id);if(type==='shell')return state.data.sessions.flatMap(s=>(s.shells||[]).map(sh=>({...sh,session:s}))).find(x=>x.id===id);if(type==='history')return state.data.history.find(x=>x.id===id);return state.data.core;}

function rail(){return `<aside class="rail"><div class="rail-logo">t_</div><nav aria-label="主导航">${[['resources','资源'],['sessions','会话'],['history','历史']].map(([k,l])=>`<button data-section="${k}" class="${state.section===k?'active':''}" title="${l}" aria-label="${l}">${icon(k)}</button>`).join('')}</nav><div class="rail-bottom"><button data-select="core:core" title="Core 管理">${icon('core')}</button><button data-section="settings" title="设置">${icon('settings')}</button></div></aside>`;}
function explorer(){const q=state.filter.trim().toLowerCase();return `<aside class="explorer"><div class="explorer-head"><div><span>资源管理器</span><small>TERMCP CORE</small></div><button class="icon-btn" data-open="session" title="新建会话">${icon('plus',15)}</button></div><label class="search">${icon('search',14)}<input type="search" placeholder="筛选资源" value="${esc(state.filter)}" data-filter></label><div class="tree-scroll">${tree(q)}</div><button class="core-card ${state.selected.type==='core'?'selected':''}" data-select="core:core"><span>${dot(state.data.core.running?'running':'error')}<b>Local core</b><small>${state.data.core.managed?'程序集成':'外部接入'}</small></span><span class="core-counts"><b>${state.data.sessions.length}</b> 会话 · <b>${shellCount()}</b> Shell</span></button></aside>`;}
function tree(q){if(state.section==='history')return group('历史记录',state.data.history.filter(x=>match(x.name,q)).map(historyNode).join(''));if(state.section==='sessions')return group('运行中的会话',state.data.sessions.filter(x=>match(x.name,q)).map(sessionNode).join(''));if(state.section==='settings')return '<div class="tree-empty">应用与 Core 设置</div>';const cs=state.data.connections.filter(c=>match(`${c.name} ${c.host||''} ${c.user||''}`,q)),sessions=state.data.sessions.filter(s=>match(`${s.name} ${s.id}`,q)),history=state.data.history.filter(h=>match(`${h.name} ${h.reason||''}`,q)).slice(0,4);return group('连接配置',cs.map(connectionNode).join(''))+group('运行中的会话',sessions.map(sessionNode).join(''))+group('最近历史',history.map(historyNode).join(''));}
const group=(n,c)=>`<section class="tree-group"><header><span>⌄</span>${n}</header>${c||'<p>没有资源</p>'}</section>`;
function connectionNode(c){const key=`connection:${c.name}`,open=state.expanded.has(key),sessions=state.data.sessions.filter(s=>s.ssh_endpoint===c.name||(c.kind==='internal'&&s.ssh_endpoint==='internal'));return `<div class="tree-node"><div class="tree-row-wrap"><button class="disclosure-button ${open?'open':''}" data-toggle="${esc(key)}" aria-label="${open?'收起':'展开'} ${esc(c.name)}">${icon('chevron',12)}</button><button class="tree-row ${state.selected.type==='connection'&&state.selected.id===c.name?'selected':''}" data-select="connection:${esc(c.name)}"><span class="resource-icon ${c.kind}">${c.kind==='internal'?'›_':'⌁'}</span><span><b>${esc(c.name)}</b><small>${esc(c.kind==='internal'?'本机':c.host||'SSH')}</small></span>${dot('running')}</button></div>${open?`<div class="tree-children">${sessions.map(sessionNode).join('')||'<p>没有可归属的会话</p>'}</div>`:''}</div>`;}
function sessionNode(s){const key=`session:${s.id}`,open=state.expanded.has(key);return `<div class="tree-node"><div class="tree-row-wrap"><button class="disclosure-button ${open?'open':''}" data-toggle="${esc(key)}" aria-label="${open?'收起':'展开'} ${esc(s.name)}">${icon('chevron',11)}</button><button class="tree-row sub ${state.selected.type==='session'&&state.selected.id===s.id?'selected':''}" data-select="session:${esc(s.id)}">${dot(s.status)}<span><b>${esc(s.name)}</b><small>${esc(s.mode)} · ${(s.shells||[]).length} Shell</small></span></button></div>${open?`<div class="tree-children shells">${(s.shells||[]).map(sh=>`<button class="tree-row leaf ${state.selected.type==='shell'&&state.selected.id===sh.id?'selected':''}" data-select="shell:${esc(sh.id)}"><span class="terminal-glyph">›_</span><span><b>${esc(sh.name||'shell')}</b><small>${esc(sh.status)}</small></span></button>`).join('')||'<p>没有 Shell</p>'}</div>`:''}</div>`;}
const historyNode=h=>`<button class="tree-row leaf ${state.selected.type==='history'&&state.selected.id===h.id?'selected':''}" data-select="history:${esc(h.id)}">${icon('history',13)}<span><b>${esc(h.name)}</b><small>${esc(h.reason||'archived')}</small></span></button>`;

const head=(title,eye,actions='')=>`<header class="content-head"><div><div class="eyebrow">${eye}</div><h1>${esc(title)}</h1></div><div class="head-actions">${actions}</div></header>`;
function workspace(){if(state.section==='settings')return settingsPage();const r=selected();return ({core:corePage,connection:connectionPage,session:sessionPage,shell:shellPage,history:historyPage}[state.selected.type]||emptyPage)(r);}
function corePage(c){const act=c.managed?`<button class="button" data-action="restart-core">${icon('refresh',14)}重启 Core</button>`:'';return `${head('Local core','CORE INSTANCE',act)}<div class="metrics"><article><span>运行状态</span><b>${dot(c.running?'running':'error')}${c.running?'运行中':'不可用'}</b><small>${c.managed?'由 GUI 托管':'连接现有 Core'}</small></article><article><span>活跃会话</span><strong>${state.data.sessions.length}</strong><small>${shellCount()} 个运行中 Shell</small></article><article><span>端口转发</span><strong>${state.data.forwards.length}</strong><small>跟随会话生命周期</small></article></div><section class="panel core-overview"><div><span>服务地址</span><code>${esc(c.address)}</code></div><div><span>接入模式</span><b>${c.managed?'程序集成':'外部接入'}</b></div><div><span>数据来源</span><b>${state.data.preview?'浏览器预览':'termcp REST API'}</b></div></section>${resourceGrid()}`;}
function connectionPage(c){if(!c)return emptyPage();const ss=state.data.sessions.filter(s=>s.ssh_endpoint===c.name||(c.kind==='internal'&&s.ssh_endpoint==='internal'));return `${head(c.name,'SSH CONNECTION',`<button class="button primary" data-open="session" data-connection="${esc(c.name)}">${icon('terminal',14)}连接</button>`)}<section class="connection-hero"><div class="connection-symbol">${c.kind==='internal'?'›_':'⌁'}</div><div><span>${c.kind==='internal'?'本机连接':'SSH 主机'}</span><h2>${esc(c.kind==='internal'?'Core 所在本机':`${c.user||''}@${c.host||''}:${c.port||22}`)}</h2><p>${esc(c.description||'连接凭据由 termcp Core 管理，GUI 不读回敏感字段。')}</p></div>${dot('running')}</section><div class="section-title"><h2>关联会话</h2><span>${ss.length}</span></div><div class="session-cards">${ss.map(sessionCard).join('')||'<div class="empty-state">Core 未提供会话与此连接配置的归属信息；运行中的会话仍可从资源树访问。</div>'}</div>`;}
function sessionPage(s){if(!s)return emptyPage();return `${head(s.name,'ACTIVE SESSION',`<button class="button" data-action="new-shell" data-id="${esc(s.id)}">${icon('plus',14)}新建 Shell</button><button class="button danger" data-action="terminate" data-id="${esc(s.id)}">结束会话</button>`)}<div class="session-summary"><div><span>${dot(s.status)}${esc(s.status)}</span><code>termcp://#${esc(s.id)}</code></div><dl><div><dt>连接类型</dt><dd>${esc(s.ssh_endpoint||'remote')}</dd></div><div><dt>终端模式</dt><dd>${esc(s.mode)}</dd></div><div><dt>Shell</dt><dd>${(s.shells||[]).length}</dd></div></dl></div><div class="section-title"><h2>Shell 资源</h2><span>共享一条连接</span></div><div class="shell-grid">${(s.shells||[]).map((sh,i)=>shellCard(sh,s,i)).join('')||'<div class="empty-state">会话还没有 Shell。</div>'}</div>`;}
function shellPage(sh){if(!sh)return emptyPage();const i=sh.session.shells.findIndex(x=>x.id===sh.id)+1;return `${head(sh.name||'shell','TERMINAL SHELL')}<section class="terminal-preview"><header><span>${dot(sh.status)}${esc(sh.session.name)} / ${esc(sh.name)}</span><code>termcp://#${esc(sh.session.id)}:${i}</code></header><pre><span>termcp gui</span> 已连接到 Core\n\n当前 Shell 状态：<b>${esc(sh.status)}</b>\n终端流将在下一阶段通过 /api/ui/ws 接入。\n\n<span class="prompt">›</span> <i>等待终端输出…</i></pre><footer><span>PTY · ${esc(sh.mode)}</span><span>人和 Agent 共享输入</span></footer></section>`;}
function historyPage(h){if(!h)return emptyPage();return `${head(h.name,'SESSION HISTORY')}<section class="panel history-detail"><span class="archive-badge">只读归档</span><dl><div><dt>原因</dt><dd>${esc(h.reason||'archived')}</dd></div><div><dt>连接</dt><dd>${esc(h.ssh_endpoint||'remote')}</dd></div><div><dt>资源</dt><dd><code>termcp://#${esc(h.id)}</code></dd></div></dl><p>历史正文、搜索和截图将在后续阶段接入。</p></section>`;}
function settingsPage(){return `${head('应用设置','TERMCP GUI')}<section class="panel settings-list"><div><span><b>Core 模式</b><small>默认启动程序集成 Core；端口被占用时连接现有实例。</small></span><em>${state.data.core.managed?'程序集成':'外部接入'}</em></div><div><span><b>界面风格</b><small>资源管理器布局、紧凑操作栏和原生窗口控件。</small></span><em>系统主题</em></div><div><span><b>自动刷新</b><small>当前纵向切片手动刷新；事件推送在终端阶段接入。</small></span><em>手动</em></div></section>`;}
function emptyPage(){return `${head('选择资源','RESOURCE EXPLORER')}<div class="empty-state large">从左侧选择连接、会话、Shell 或历史记录。</div>`;}
function resourceGrid(){return `<div class="section-title"><h2>资源总览</h2><button class="text-btn" data-section="resources">在树中查看</button></div><div class="resource-grid">${[['⌁',state.data.connections.length,'连接配置'],['▣',state.data.sessions.length,'活跃会话'],['›_',shellCount(),'运行中 Shell'],['◷',state.data.history.length,'历史记录']].map(x=>`<article><span class="resource-big">${x[0]}</span><div><b>${x[1]}</b><small>${x[2]}</small></div></article>`).join('')}</div>`;}
const sessionCard=s=>`<button class="session-card" data-select="session:${esc(s.id)}"><span class="session-icon">${icon('terminal',18)}</span><span><b>${esc(s.name)}</b><small>${esc(s.ssh_endpoint)} · ${(s.shells||[]).length} Shell</small></span>${dot(s.status)}</button>`;
const shellCard=(sh,s,i)=>`<button class="shell-card" data-select="shell:${esc(sh.id)}"><span>›_</span><div><b>${esc(sh.name||`shell-${i+1}`)}</b><small>${esc(sh.mode)} · ${esc(sh.status)}</small><code>termcp://#${esc(s.id)}:${i+1}</code></div>${dot(sh.status)}</button>`;

function modal(){if(!state.dialog)return '';if(state.dialog.type==='session')return `<div class="modal-backdrop"><form class="modal" data-form="session"><header><div><span>NEW SESSION</span><h2>连接主机</h2></div><button type="button" class="icon-btn" data-close>×</button></header><label>连接配置<select name="connection">${state.data.connections.map(c=>`<option value="${esc(c.name)}" ${state.dialog.connection===c.name?'selected':''}>${esc(c.name)} · ${esc(c.kind==='internal'?'本机':c.host)}</option>`).join('')}</select></label><label>会话名称<input name="name" placeholder="使用连接配置名称"></label><label>启动命令<input name="command" placeholder="留空打开默认 Shell"></label><footer><button type="button" class="button" data-close>取消</button><button class="button primary" type="submit">连接并打开</button></footer></form></div>`;if(state.dialog.type==='shell')return `<div class="modal-backdrop"><form class="modal compact" data-form="shell"><header><div><span>NEW SHELL</span><h2>在当前连接上新建 Shell</h2></div><button type="button" class="icon-btn" data-close>×</button></header><input type="hidden" name="session" value="${esc(state.dialog.session)}"><label>Shell 名称<input name="name" value="bash" required></label><p>不会建立新的 SSH 连接。</p><footer><button type="button" class="button" data-close>取消</button><button class="button primary" type="submit">创建 Shell</button></footer></form></div>`;return `<div class="modal-backdrop"><div class="modal compact"><header><div><span>END SESSION</span><h2>结束当前会话？</h2></div><button type="button" class="icon-btn" data-close>×</button></header><p>所有 Shell 和转发会被关闭，输出保留到历史记录。</p><footer><button class="button" data-close>取消</button><button class="button danger" data-confirm-terminate="${esc(state.dialog.session)}">结束并归档</button></footer></div></div>`;}

function render(){document.querySelector('#app').innerHTML=`<div class="app-shell"><header class="titlebar" style="--wails-draggable:drag"><div class="title-brand"><span>t_</span><b>termcp gui</b></div><div class="title-status">${dot(state.data.core.running?'running':'error')}<span>${state.data.core.running?'Core 运行中':'Core 不可用'}</span><small>${state.data.core.managed?'程序集成':'外部接入'}</small></div><div class="window-controls" style="--wails-draggable:no-drag"><button data-window="min" aria-label="最小化">—</button><button data-window="max" aria-label="最大化">□</button><button data-window="close" aria-label="关闭">×</button></div></header><div class="body">${rail()}${explorer()}<main class="content">${state.error?`<div class="error-banner">${esc(state.error)}<button data-action="refresh">重试</button></div>`:''}<div class="content-toolbar"><span>${state.data.preview?'浏览器预览 · 演示资源':'实时 Core 数据'}</span><button class="icon-btn ${state.loading?'spinning':''}" data-action="refresh" title="刷新资源">${icon('refresh',15)}</button></div>${workspace()}</main></div></div>${modal()}`;}
function toast(text){const el=document.querySelector('#toast');el.textContent=text;el.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.hidden=true,2800);}
async function action(label,fn){try{await fn();toast(label);await refresh();}catch(e){toast(String(e));}}

document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.section){state.section=b.dataset.section;if(state.section==='settings')state.selected={type:'settings',id:'settings'};render();return;}if(b.dataset.select){const [type,...id]=b.dataset.select.split(':');state.selected={type,id:id.join(':')};render();return;}if(b.dataset.toggle){e.stopPropagation();state.expanded.has(b.dataset.toggle)?state.expanded.delete(b.dataset.toggle):state.expanded.add(b.dataset.toggle);render();return;}if(b.dataset.open==='session'){state.dialog={type:'session',connection:b.dataset.connection||''};render();return;}if(b.dataset.close!==undefined){state.dialog=null;render();return;}if(b.dataset.window){const calls={min:'WindowMinimise',max:'WindowToggleMaximise',close:'WindowClose'};if(bridge.available())bridge.call(calls[b.dataset.window]);return;}if(b.dataset.action==='refresh'){refresh();return;}if(b.dataset.action==='restart-core'){action('Core 已重启',()=>bridge.call('RestartCore'));return;}if(b.dataset.action==='new-shell'){state.dialog={type:'shell',session:b.dataset.id};render();return;}if(b.dataset.action==='terminate'){state.dialog={type:'terminate',session:b.dataset.id};render();return;}if(b.dataset.confirmTerminate){const id=b.dataset.confirmTerminate;state.dialog=null;action('会话已归档',()=>bridge.call('TerminateSession',id));}});
document.addEventListener('input',e=>{if(e.target.matches('[data-filter]')){state.filter=e.target.value;document.querySelector('.tree-scroll').innerHTML=tree(state.filter.trim().toLowerCase());}});
document.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target);if(e.target.dataset.form==='session'){state.dialog=null;action('会话已创建',()=>bridge.call('CreateSession',{connection:d.get('connection'),name:d.get('name'),command:d.get('command')}));}if(e.target.dataset.form==='shell'){state.dialog=null;action('Shell 已创建',()=>bridge.call('CreateShell',d.get('session'),d.get('name')));}});
render();refresh();
