const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons = { core:'◈', sessions:'▤', workspace:'>_', connections:'⌁', history:'◷', notifications:'◇', mcp:'{}', settings:'⚙' };
const labels = {core:'Core 管理',sessions:'会话',workspace:'SSH 工作台',connections:'主机管理',history:'历史记录',notifications:'通知规则',mcp:'API / MCP',settings:'运行设置'};
const concepts = {
  control:{name:'控制中心',tag:'01 / CONTROL CENTER',title:'先管理内核，再进入工作。',desc:'Core 的状态、运行参数与会话入口集中呈现，让 termcp 从命令行服务变成可管理的桌面产品。',tags:['Core 生命周期','清晰的功能导航','推荐作为产品骨架'],page:'core'},
  studio:{name:'SSH 工作台',tag:'02 / SSH WORKSPACE',title:'一个工作台，连接每一台主机。',desc:'用 termcp 管理 SSH 连接，把不同主机与 Shell 放进标签、分屏和平铺工作区。',tags:['主机分组与收藏','终端分屏与平铺','Core 统一管理'],page:'workspace'},
  explorer:{name:'资源管理器',tag:'03 / RESOURCE EXPLORER',title:'连接、会话、Shell，一层层展开。',desc:'用资源树组织多个 core 和远程连接，让连接模板与运行中的会话各有归属，定位后直接操作。',tags:['多 Core 视角','明确资源层级','适合多环境管理'],page:'workspace'}
};
const initialState = () => ({concept:'studio',page:'workspace',core:'local',running:true,tool:'files',session:'s-demo-01',shell:'sh-demo-01',input:false,inspectorTab:'monitor',inspectorCollapsed:false,terminalMinimized:false,query:'',historyQuery:'',ssh:initialSSHState(),config:{host:'127.0.0.1',port:'18765',dataDir:'~/.termcp',log:'info',internal:true,manage:false},sessions:[
  {id:'s-demo-01',name:'API 开发',connection:'dev-server',host:'dev.example.test',kind:'remote',shells:[{id:'sh-demo-01',name:'build',exited:false},{id:'sh-demo-02',name:'logs',exited:false}],waiting:true},
  {id:'s-demo-02',name:'本地工作区',connection:'internal',host:'本机',kind:'internal',shells:[{id:'sh-demo-03',name:'zsh',exited:false}],waiting:false},
  {id:'s-demo-03',name:'服务观测',connection:'staging',host:'staging.example.test',kind:'remote',shells:[{id:'sh-demo-04',name:'monitor',exited:false}],waiting:false}
],connections:[{name:'internal',host:'termcp 所在本机',kind:'internal',user:'—',group:'本机',port:22,favorite:false},{name:'dev-server',host:'dev.example.test',kind:'remote',user:'developer',group:'开发',port:22,auth:'私钥 PEM 内容',favorite:true},{name:'staging',host:'staging.example.test',kind:'remote',user:'operator',group:'预发布',port:22,auth:'私钥 PEM 内容',favorite:true}],history:[{id:'h-demo-01',name:'构建验证',connection:'dev-server',time:'今天 09:32',tag:'release',reason:'正常退出'},{id:'h-demo-02',name:'数据库迁移',connection:'staging',time:'昨天 18:10',tag:'database',reason:'手动结束'},{id:'h-demo-03',name:'网络排查',connection:'staging',time:'昨天 14:26',tag:'network',reason:'SSH 断线'}],rules:[{id:'n-demo-01',session:'API 开发',shell:'build',event:'输出静默 · 3 秒',channel:'resource'},{id:'n-demo-02',session:'服务观测',shell:'monitor',event:'进程退出',channel:'sampling'}],files:[{session:'s-demo-01',name:'src/',type:'目录',size:'—'},{session:'s-demo-01',name:'package.json',type:'文件',size:'1.2 KB'},{session:'s-demo-01',name:'README.md',type:'文件',size:'3.4 KB'}],forwards:[{session:'s-demo-01',id:'f-demo-01',kind:'Local · -L',source:'127.0.0.1:3000',target:'127.0.0.1:3000'}],output:{},events:[{time:'10:42',text:'API 开发等待人工输入',detail:'notify_user · sudo 密码提示'},{time:'10:38',text:'新建 Shell：logs',detail:'API 开发 / dev-server'},{time:'10:30',text:'Core 已启动',detail:'127.0.0.1:18765 · 演示'}]});
let state = initialState();
let toastTimer;
const current = () => state.sessions.find(s => s.id === state.session);
const currentFiles = () => state.files.filter(f=>f.session===state.session);
const currentForwards = () => state.forwards.filter(f=>f.session===state.session);
const owned = () => state.core === 'local';
const available = () => owned() && state.running;
const allShells = () => state.sessions.reduce((n,s)=>n+s.shells.filter(sh=>!sh.exited).length,0);
const button = (text, action, cls='', extra='') => `<button class="${cls}" data-action="${action}" ${extra}>${text}</button>`;
const controlIcons = {
  add:'<path d="M12 5v14M5 12h14"/>',
  star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1 6.2-5.5-2.9-5.5 2.9 1-6.2L3 9.6l6.2-.9Z"/>',
  edit:'<path d="m15 5 4 4M4 20l5-1L20 8l-4-4L5 15Z"/>',
  splitH:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16"/>',
  splitV:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 12h18"/>',
  grid:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M12 4v16M3 12h18"/>',
  restore:'<path d="M8 8V4h12v12h-4"/><rect x="4" y="8" width="12" height="12" rx="1"/>',
  settings:'<path d="M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8Z"/><path d="m10 3-.7 2.2-2 .9-2.1-.6-2 3.5 1.6 1.6v2.8l-1.6 1.6 2 3.5 2.1-.6 2 .9.7 2.2h4l.7-2.2 2-.9 2.1.6 2-3.5-1.6-1.6v-2.8l1.6-1.6-2-3.5-2.1.6-2-.9L14 3Z"/>',
  copy:'<rect x="8" y="8" width="12" height="12" rx="2"/><path d="M16 8V4H4v12h4"/>',
  minimize:'<path d="M5 12h14"/>',
  expand:'<rect x="5" y="5" width="14" height="14" rx="2"/>',
  panel:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M15 4v16m-5-11 3 3-3 3"/>',
  close:'<path d="m6 6 12 12M18 6 6 18"/>',
  interrupt:'<rect x="6" y="6" width="12" height="12" rx="2"/>',
  logs:'<path d="M5 5h14M5 10h14M5 15h9M5 20h9"/>',
  restart:'<path d="M20 7v5h-5M4 17v-5h5M6 7a7 7 0 0 1 12-2l2 2M18 17a7 7 0 0 1-12 2l-2-2"/>',
  power:'<path d="M12 3v9M6.4 5.4a8 8 0 1 0 11.2 0"/>'
};
const iconButton = (label,action,icon,extra='',cls='') => `<button class="compact-button ${cls}" data-action="${action}" aria-label="${label}" title="${label}" ${extra}><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${controlIcons[icon]}</svg></button>`;
const badge = (text,type='') => `<span class="badge ${type}">${text}</span>`;
const head = (title,sub,actions='') => `<div class="page-head"><div><h2>${title}</h2><p>${sub}</p></div><div class="actions">${actions}</div></div>`;
const toast = (text) => { $('#toast').textContent=text; $('#toast').hidden=false; clearTimeout(toastTimer); toastTimer=setTimeout(()=>$('#toast').hidden=true,3500); };
function openDialog(title, body, actions='') {
  $('#dialog-body').innerHTML=`<div class="dialog-head"><h2>${title}</h2>${button('×','close-dialog','','aria-label="关闭对话框"')}</div>${body}${actions?`<div class="dialog-actions">${actions}</div>`:''}`;
  if(!$('#dialog').open)$('#dialog').showModal();
}
function closeDialog(){ $('#dialog').close(); }
function event(text,detail){state.events.unshift({time:'现在',text,detail});state.events=state.events.slice(0,6);}
function navigate(page){state.page=page;state.query='';render();}
function sidebar() {
  const count={sessions:available()?state.sessions.length:0,notifications:available()?state.rules.length:0};
  const nav = (keys) => `<nav class="side-nav" aria-label="功能导航">${keys.map(k=>`<button data-page="${k}" class="${state.page===k?'active':''}" ${state.page===k?'aria-current="page"':''}><span class="icon" aria-hidden="true">${icons[k]}</span>${labels[k]}${count[k]!==undefined?`<span class="nav-count">${count[k]}</span>`:''}</button>`).join('')}</nav>`;
  let primary = nav(['core','sessions','workspace','connections','history','notifications']);
  if(state.concept==='explorer') primary=`<div><div class="tree-label">RESOURCE TREE ${button('+','new-session','quiet','aria-label="新建会话"')}</div><div class="tree"><button data-page="core"><span class="branch">⌄</span><span class="dot ${state.running?'':'gray'}"></span>Local core</button>${state.connections.map(c=>`<button class="level1" data-action="connection-detail" data-id="${escapeHtml(c.name)}"><span class="branch">⌄</span>${escapeHtml(c.name)}</button>${state.sessions.filter(s=>s.connection===c.name&&available()).map(s=>`<button class="level2 ${s.id===state.session&&state.page==='workspace'?'selected':''}" data-action="select-session" data-id="${s.id}"><span class="dot ${s.waiting?'amber':''}"></span>${escapeHtml(s.name)}</button>${s.id===state.session?s.shells.map(sh=>`<button class="level3 ${state.shell===sh.id?'selected':''}" data-shell="${sh.id}"><span class="branch">└</span>&gt;_ ${escapeHtml(sh.name)} ${sh.exited?'· 已退出':''}</button>`).join(''):''}`).join('')}`).join('')}<button data-action="switch-core" data-id="remote"><span class="branch">›</span><span class="dot gray"></span>Remote core · 未连接</button></div></div>${nav(['core','sessions','connections','history','notifications'])}`;
  if(state.concept==='studio')primary=nav(['workspace','connections','sessions','history'])+hostNavigation()+'';
  return `<aside class="sidebar"><div class="side-brand"><span class="brand-mark">T_</span>Termcp</div><button class="core-picker" data-action="cores"><span>${owned()?'Local core':'Remote core'}<small>${owned()?'托管实例 · 本机':'外部实例 · 未连接'}</small></span><span>⌄</span></button><div><div class="nav-label">${state.concept==='explorer'?'RESOURCES':'WORKSPACE'}</div>${primary}</div><div class="sidebar-bottom">${nav(state.concept==='studio'?['core','mcp','settings']:['mcp','settings'])}<div class="core-mini"><span class="dot ${available()?'':'gray'}"></span>${available()?'Core 运行中':owned()?'Core 已停止':'实例未连接'}<br><small>演示版本 · :${escapeHtml(state.config.port)}</small></div></div></aside>`;
}
function render(){
  reconcileWorkspaces();
  const c=concepts[state.concept];
  document.querySelectorAll('[data-concept]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.concept===state.concept)));
  $('#concept-intro').innerHTML=`<div><div class="eyebrow">${c.tag}</div><h1>${c.title}</h1><p>${c.desc}</p></div><div class="concept-tags">${c.tags.map(t=>`<span>${t}</span>`).join('')}</div>`;
  $('#app').className=`app-window ${state.concept}`;
  $('#app').innerHTML=`<div class="window-bar"><div class="traffic" aria-hidden="true"><i></i><i></i><i></i></div><span class="window-title">Termcp <span style="opacity:.4">/</span> ${labels[state.page]}</span><span class="demo">PROTOTYPE</span></div><div class="app-layout">${sidebar()}<main class="main" id="main-content">${pageContent()}</main></div>`;
}
function runtime(){return `<div class="top-runtime"><span><span class="dot ${available()?'':'gray'}"></span>${owned()?'Local core · 托管':'Remote core · 外部'}</span><span>${available()?'运行中':'未连接'} / :${escapeHtml(state.config.port)}</span>${iconButton('管理 Core','go-core','settings')}</div>`;}
function pageContent(){return ({core:corePage,sessions:sessionsPage,workspace:workspacePage,connections:connectionsPage,history:historyPage,notifications:notificationsPage,mcp:mcpPage,settings:settingsPage})[state.page]();}
function corePage(){
  return head('Core 管理','GUI 管理服务进程，core 管理持久会话与终端。',button('＋ 添加 Core','add-core'))+
  `<section class="core-hero"><div>${badge(available()?'<span class="dot"></span> 运行中':owned()?'已停止':'未连接',available()?'':'neutral')} ${badge(owned()?'GUI 托管':'外部接入','neutral')}<h3>${owned()?'Local core':'Remote core'}</h3><div class="address">${owned()?`http://${escapeHtml(state.config.host)}:${escapeHtml(state.config.port)}`:'https://core.example.test'}</div><div class="hero-meta"><span>版本<b>演示构建</b></span><span>数据目录<b>${escapeHtml(state.config.dataDir)}</b></span><span>日志级别<b>${escapeHtml(state.config.log)}</b></span></div></div><div class="actions">${owned()?state.running?iconButton('查看 Core 日志','core-logs','logs')+iconButton('重启 Core','restart','restart')+iconButton('停止 Core','stop','power','','danger'):button('启动 Core','start','primary')+button('运行设置','go-settings'):button('连接实例','connect-remote','primary')}</div></section>`+
  `${!owned()?'<div class="mode-note">外部 core 的启动、停止和升级由其宿主管理；GUI 只连接服务接口。此原型可演示连接失败与返回本地实例。</div>':''}`+
  `<div class="stats"><div class="stat"><span>活跃会话</span><strong>${available()?state.sessions.length:'—'}</strong></div><div class="stat"><span>运行中 Shell</span><strong>${available()?allShells():'—'}</strong></div><div class="stat"><span>端口转发</span><strong>${available()?state.forwards.length:'—'}</strong></div></div>`+
  `${available()?`${state.sessions.some(s=>s.waiting)?`<div class="attention"><span class="icon" aria-hidden="true">◇</span><p><b>有会话需要你处理</b><br>API 开发收到人工输入提醒，点击打开对应终端。</p>${button('打开终端 →','waiting')}</div>`:''}<div class="section-head"><h3>运行中的会话</h3>${button('查看全部 →','go-sessions','quiet')}</div>${sessionTable(state.sessions.slice(0,3))}`:`<div class="empty"><h3>${owned()?'从启动 core 开始':'连接一个已有 core'}</h3><p>${owned()?'启动后可创建会话、打开终端和接入 MCP 客户端。':'检查服务地址与认证 Token，再建立连接。'}</p>${button(owned()?'启动 Local core':'连接实例',owned()?'start':'connect-remote','primary')}</div>`}`+
  `<div class="two-col"><section><div class="section-head"><h3>服务入口</h3>${button('配置 MCP ↗','go-mcp','quiet')}</div><div class="panel"><div class="list-line"><span>REST / WebSocket</span>${badge(available()?'可用':'不可用',available()?'':'neutral')}</div><div class="list-line"><span>MCP · Streamable HTTP</span><code>/stream</code></div><div class="list-line"><span>MCP · SSE</span><code>/sse</code></div></div></section><section><div class="section-head"><h3>最近事件</h3><small>GUI 本地事件 · 演示</small></div>${state.events.slice(0,3).map(e=>`<div class="event-line"><time>${e.time}</time><div>${escapeHtml(e.text)}<small>${escapeHtml(e.detail)}</small></div></div>`).join('')}</section></div>`;
}
function sessionTable(sessions){return `<div class="table-wrap"><table><thead><tr><th>会话 / 连接</th><th>状态</th><th>Shell</th><th>操作</th></tr></thead><tbody>${sessions.map(s=>`<tr><td><div class="name-cell"><span class="session-symbol">&gt;_</span><div>${escapeHtml(s.name)}<small>${escapeHtml(s.connection)} · ${escapeHtml(s.host)}</small></div></div></td><td>${badge(s.waiting?'需人工输入':'运行中',s.waiting?'warn':'')}</td><td>${s.shells.filter(sh=>!sh.exited).length} 个</td><td><div class="actions">${button('打开 →','select-session','','data-id="'+s.id+'"')}${button('结束','end-session','quiet','data-id="'+s.id+'"')}</div></td></tr>`).join('')}</tbody></table></div>`;}
function sessionsPage(){return head('会话','一个会话对应一条连接，多个 Shell 共享该连接。',button('＋ 新建会话','new-session','primary',!available()?'disabled':''))+runtime()+(!available()?'<div class="empty">当前 core 不可用，请先启动或连接实例。</div>':`<label class="field" style="max-width:300px">查找会话<input data-filter="sessions" type="search" value="${escapeHtml(state.query)}" placeholder="名称或连接配置"></label><div id="session-results">${sessionResults()}</div>`);}
function sessionResults(){const list=state.sessions.filter(s=>(s.name+' '+s.connection).toLowerCase().includes(state.query.toLowerCase()));return list.length?sessionTable(list):'<div class="empty">没有匹配的会话。</div>';}
function workspacePage(){return sshWorkspacePage();}

function inspector(s,sh){return hostInspector(s,sh);}
function toolContent(s){
  if(state.tool==='files')return `<div class="section-head"><div class="path">~/workspace</div><div class="actions">${button('＋ 目录','new-folder')}${button('添加演示文件','upload-file')}</div></div><div class="table-wrap"><table><thead><tr><th>名称</th><th>类型</th><th>大小</th><th></th></tr></thead><tbody>${currentFiles().map((f,i)=>`<tr><td>${f.type==='目录'?'▱':'▤'} &nbsp;${escapeHtml(f.name)}</td><td>${f.type}</td><td>${f.size}</td><td>${button(f.type==='目录'?'打开':'预览','file-preview','quiet','data-id="'+i+'"')}</td></tr>`).join('')}</tbody></table></div>`;
  if(state.tool==='forwards')return `<div class="section-head"><span>当前会话的转发</span>${button('＋ 添加转发','add-forward')}</div>${currentForwards().length?`<div class="table-wrap"><table><thead><tr><th>类型</th><th>监听地址</th><th>目标地址</th><th></th></tr></thead><tbody>${currentForwards().map(f=>`<tr><td>${f.kind}</td><td><code>${escapeHtml(f.source)}</code></td><td><code>${escapeHtml(f.target)}</code></td><td>${button('关闭','delete-forward','quiet','data-id="'+f.id+'"')}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">还没有端口转发。</div>'}`;
  const rules=state.rules.filter(r=>r.session===s.name);return `<div class="section-head"><span>MCP 客户端注册的唤醒规则</span>${button('查看全部','go-notifications','quiet')}</div>${rules.length?ruleTable(rules):'<div class="empty">当前会话没有注册通知规则。</div>'}`;
}
function connectionsPage(){return sshHostsPage();}

function historyPage(){return head('历史记录','会话结束后保留输出；只有显式删除才清理历史。')+runtime()+(!available()?'<div class="empty">当前 core 不可用。连接后可读取已持久化的历史。</div>':`<label class="field" style="max-width:340px">查找归档会话<input data-filter="history" type="search" value="${escapeHtml(state.historyQuery)}" placeholder="名称、连接配置或标签"></label><div id="history-results">${historyResults()}</div>`);}
function historyResults(){const list=state.history.filter(h=>(h.name+' '+h.connection+' '+h.tag).toLowerCase().includes(state.historyQuery.toLowerCase()));return list.length?`<div class="table-wrap"><table><thead><tr><th>会话</th><th>结束时间</th><th>原因</th><th>标签</th><th></th></tr></thead><tbody>${list.map(h=>`<tr><td>${escapeHtml(h.name)}<small>${escapeHtml(h.connection)}</small></td><td>${h.time}</td><td>${escapeHtml(h.reason)}</td><td>${badge(escapeHtml(h.tag||'未标记'),'neutral')}</td><td><div class="actions">${button('查看输出','history-preview','','data-id="'+h.id+'"')}${button('编辑','history-edit','quiet','data-id="'+h.id+'"')}${button('删除','history-delete','quiet','data-id="'+h.id+'"')}</div></td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">没有匹配的历史记录。</div>';}
function ruleTable(rules){return `<div class="table-wrap"><table><thead><tr><th>会话 / Shell</th><th>触发条件</th><th>通知通道</th><th></th></tr></thead><tbody>${rules.map(r=>`<tr><td>${escapeHtml(r.session)}<small>${escapeHtml(r.shell)}</small></td><td>${r.event}</td><td><code>${r.channel}</code></td><td>${button('移除规则','remove-rule','quiet','data-id="'+r.id+'"')}</td></tr>`).join('')}</tbody></table></div>`;}
function notificationsPage(){return head('通知规则','由 MCP shell_notify 注册，GUI 查看并移除规则。')+runtime()+(!available()?'<div class="empty">当前 core 不可用。</div>':`${state.rules.length?ruleTable(state.rules):'<div class="empty">没有已注册的通知规则。</div>'}<div class="mode-note">这些规则唤醒 MCP 客户端。notify_user 的人工输入提醒直接定位到会话和 Shell。</div>`);}
function mcpConfig(){return JSON.stringify({mcpServers:{termcp:{type:'http',url:`http://${state.config.host}:${state.config.port}/stream`}}},null,2);}
function mcpPage(){return head('API / MCP','GUI 和 Agent 连接同一个 core，操作同一批会话。',button('复制 MCP 配置','copy-mcp','primary'))+runtime()+`<div class="two-col"><div class="panel"><h3>Streamable HTTP</h3>${badge('HTTP · /stream')}<pre class="config-code">${escapeHtml(mcpConfig())}</pre><p class="note">启用认证后，需要在客户端配置 Authorization: Bearer 请求头。</p></div><div><div class="panel"><h3>服务地址</h3><div class="list-line"><span>REST API</span><code>/api/*</code></div><div class="list-line"><span>终端 I/O</span><code>/api/ui/ws</code></div><div class="list-line"><span>兼容 SSE</span><code>/sse</code></div></div><div class="section-head"><h3>准确交接资源</h3></div><div class="resource-url"><span>termcp://#s-demo-01</span>${button('复制','copy-example')}</div><p class="note">资源 URL 标识配置、会话或 Shell。地址的解析由 core 完成，不包含认证 Token。</p></div></div>`;}
function settingsPage(){return head('运行设置','托管实例的启动参数由 GUI 保存，应用时重启 core。',button('保存并应用','save-settings','primary',!owned()?'disabled':''))+`${!owned()?'<div class="mode-note">外部实例的运行参数由宿主配置。切换到 Local core 后可体验设置。</div>':''}<form id="settings-form"><div class="settings-grid"><div class="panel"><h3>服务与存储</h3><label class="field">监听地址<input name="host" value="${escapeHtml(state.config.host)}" required></label><label class="field">HTTP 端口<input name="port" type="number" min="1" max="65535" value="${escapeHtml(state.config.port)}" required></label><label class="field">数据目录<input name="dataDir" value="${escapeHtml(state.config.dataDir)}" required><small>持久化会话输出、消息和连接配置。</small></label><label class="field">日志级别<select name="log">${['debug','info','warn','error'].map(v=>`<option ${state.config.log===v?'selected':''}>${v}</option>`).join('')}</select></label></div><div class="panel"><h3>能力与认证</h3><label class="checkbox"><input name="internal" type="checkbox" ${state.config.internal?'checked':''}><span>启用内建本机连接<br><small class="note">关闭时对应 --no-internal。</small></span></label><label class="checkbox"><input name="manage" type="checkbox" ${state.config.manage?'checked':''}><span>允许 MCP 管理 SSH 配置<br><small class="note">对应 --mcp-manage-ssh-configs。</small></span></label><label class="field">认证 Token<input name="token" type="password" autocomplete="new-password" placeholder="仅输入演示值，不会保存"><small>非 loopback 监听必须配置认证；正式产品使用系统凭据库保存。</small></label><div class="mode-note">修改设置会重启 core，中断当前连接与 Shell。历史输出保留；原会话不会自动恢复。</div><div id="settings-error" role="alert" class="error-text"></div></div></div></form>`;}
function newSession(connection=''){if(!available()){toast('请先启动或连接 core。');return;}openDialog('新建会话',`<form id="new-session-form"><label class="field">名称<input name="name" placeholder="例如：后端开发" required maxlength="60" autofocus></label><label class="field">连接配置<select name="connection">${state.connections.map(c=>`<option value="${escapeHtml(c.name)}" ${connection===c.name?'selected':''}>${escapeHtml(c.name)} · ${escapeHtml(c.host)}</option>`).join('')}</select></label><label class="field">启动命令<input name="command" value="bash" required><small>演示采用 PTY 模式；真实终端由 core 创建。</small></label></form>`,button('取消','close-dialog')+button('创建并打开','create-session','primary'));}
function archiveSessions(reason){for(const s of state.sessions)state.history.unshift({id:'h-'+s.id+'-'+Date.now(),name:s.name,connection:s.connection,time:'刚刚',tag:'',reason});state.sessions=[];state.session='';state.shell='';state.rules=[];state.forwards=[];state.input=false;}
async function copy(value){try{await navigator.clipboard.writeText(value);toast('已复制到剪贴板');}catch{openDialog('复制内容',`<textarea class="config-code" style="width:100%" readonly aria-label="待复制内容">${escapeHtml(value)}</textarea>`);}}
function connectionDetail(name){const c=state.connections.find(c=>c.name===name);if(!c)return;openDialog('连接配置 · '+escapeHtml(c.name),`<div class="list-line"><span>类型</span><span>${c.kind==='internal'?'本机':'SSH'}</span></div><div class="list-line"><span>主机</span><code>${escapeHtml(c.host)}</code></div><div class="list-line"><span>用户</span><span>${escapeHtml(c.user)}</span></div><div class="list-line"><span>凭据</span><span>${c.kind==='internal'?'内建连接':'已存储 · 不可读回（演示）'}</span></div><p class="note">${c.kind==='internal'?'内建配置由 core 提供。':'正式版将提供表单 / TOML 编辑、复制、删除与连接测试。'}</p>`,button('关闭','close-dialog')+button('测试连接','test-connection','',c.kind==='internal'?'disabled':'')+button('创建会话','session-from-connection','primary','data-id="'+escapeHtml(c.name)+'"'));}
const actions={
  'design':()=>openDialog('三种产品方向',Object.entries(concepts).map(([key,c])=>`<div class="design-choice"><strong>${c.tag} · ${c.name}</strong><p>${c.desc}</p>${button('体验这一方案','choose-concept','','data-id="'+key+'"')}</div>`).join('')+'<p class="note">默认以 SSH 工作台承载主机与终端操作，控制中心管理 core；资源树作为多环境导航模式。所有数据和操作均为模拟。</p>'),
  'choose-concept':b=>{state.concept=b.dataset.id;state.page=concepts[state.concept].page;closeDialog();render();},
  'reset':()=>{state=initialState();render();toast('演示数据已重置');},
  'close-dialog':closeDialog,
  'toggle-inspector':()=>{state.inspectorCollapsed=!state.inspectorCollapsed;render();document.querySelector('[data-action="toggle-inspector"]')?.focus();},
  'toggle-terminal':()=>{state.terminalMinimized=!state.terminalMinimized;render();document.querySelector('[data-action="toggle-terminal"]')?.focus();},
  'manage-session':()=>{const s=current();if(!s)return;const sh=s.shells.find(sh=>sh.id===state.shell);openDialog('管理会话 · '+escapeHtml(s.name),`<div class="list-line"><span>连接</span><span>${escapeHtml(s.connection)}</span></div><div class="list-line"><span>当前 Shell</span><span>${escapeHtml(sh?.name||'无')}</span></div><p class="note">关闭 Shell 仅影响当前终端；结束会话会关闭全部 Shell 和转发。Ctrl+C 不阻止后续 MCP 输入。</p>`,button('关闭','close-dialog')+button('关闭当前 Shell','close-shell','',!sh?'disabled':'')+button('结束会话','end-session','danger','data-id="'+s.id+'"'));},
  'go-core':()=>navigate('core'),'go-settings':()=>navigate('settings'),'go-sessions':()=>navigate('sessions'),'go-mcp':()=>navigate('mcp'),'go-notifications':()=>navigate('notifications'),
  'core-logs':()=>openDialog('Core 运行日志',`<div class="log-box">[INFO] core process started (demo)<br>[INFO] data directory: ${escapeHtml(state.config.dataDir)}<br>[INFO] listening on ${escapeHtml(state.config.host)}:${escapeHtml(state.config.port)}<br>[INFO] routes: REST / WebSocket / MCP<br>[INFO] ${state.sessions.length} active sessions</div><p class="note">日志为 GUI 托管进程日志的演示。</p>`),
  'start':()=>{state.running=true;event('Core 已启动','GUI 托管 · 演示');render();toast('Core 已启动（模拟）');},
  'stop':()=>openDialog('停止 Local core？',`<p class="note">将中断 ${state.sessions.length} 个会话、${allShells()} 个 Shell 与 ${state.forwards.length} 个转发。会话输出保留到历史；再次启动不会恢复原连接。</p>`,button('取消','close-dialog')+button('停止并保留历史','confirm-stop','danger')),
  'confirm-stop':()=>{archiveSessions('Core 停止');state.running=false;event('Core 已停止','会话输出保留到历史');closeDialog();render();toast('Core 已停止（模拟）');},
  'restart':()=>openDialog('重启 Local core？',`<p class="note">当前 ${state.sessions.length} 个会话将断开并保留历史。重启后请创建新会话，连接不会自动恢复。</p>`,button('取消','close-dialog')+button('确认重启','confirm-restart','primary')),
  'confirm-restart':()=>{archiveSessions('Core 重启');state.running=true;event('Core 已重启','原会话归档 · 未自动重连');closeDialog();render();toast('Core 已重启（模拟），原会话已归档');},
  'cores':()=>openDialog('选择 Core',`<div class="design-choice"><strong><span class="dot ${state.running?'':'gray'}"></span>Local core</strong><p>由 GUI 托管 · 启停与参数管理</p>${button('切换到本机','switch-core','primary','data-id="local"')}</div><div class="design-choice"><strong><span class="dot gray"></span>Remote core</strong><p>已有服务 · 只管理服务内资源 · 尚未连接</p>${button('切换到远程','switch-core','','data-id="remote"')}</div>`,button('添加已有 Core','add-core')),
  'switch-core':b=>{state.core=b.dataset.id;state.page='core';state.input=false;closeDialog();render();},
  'add-core':()=>openDialog('添加已有 Core',`<form id="core-form"><label class="field">显示名称<input name="name" value="Remote core" required></label><label class="field">服务地址<input name="url" type="url" value="https://core.example.test" required></label><label class="field">认证 Token<input name="token" type="password" placeholder="演示值，不会保存" autocomplete="new-password"></label><div class="mode-note">添加已有服务不会赋予 GUI 该服务的进程管理权限。</div><div id="connection-result" class="error-text" role="alert"></div></form>`,button('取消','close-dialog')+button('测试连接','test-core','primary')),
  'test-core':()=>{if(!$('#core-form').reportValidity())return;$('#connection-result').textContent='模拟连接失败：无法到达服务。请检查地址、网络和认证信息。';},
  'connect-remote':()=>openDialog('连接 Remote core','<div class="attention" role="alert"><p>模拟连接失败 · 无法到达 core.example.test<br>检查服务是否运行、认证 Token 是否正确，以及网络是否可达。</p></div>',button('返回 Local core','switch-core','primary','data-id="local"')),
  'new-session':()=>newSession(),
  'session-from-connection':b=>{closeDialog();newSession(b.dataset.id);},
  'create-session':()=>{const form=$('#new-session-form');if(!form.reportValidity())return;const data=new FormData(form),c=state.connections.find(c=>c.name===data.get('connection'));const id='s-demo-'+Date.now(),sh='sh-demo-'+Date.now();state.sessions.push({id,name:data.get('name').trim(),connection:c.name,host:c.host,kind:c.kind,shells:[{id:sh,name:String(data.get('command')).trim(),exited:false}],waiting:false});state.session=id;state.shell=sh;state.page='workspace';state.input=false;state.terminalMinimized=false;event('会话已创建',String(data.get('name')));closeDialog();render();toast('已创建会话（模拟）');},
  'select-session':b=>{const s=state.sessions.find(s=>s.id===b.dataset.id);if(!s)return;state.session=s.id;state.shell=s.shells[0]?.id;state.page='workspace';state.input=false;state.terminalMinimized=false;closeDialog();render();},
  'waiting':()=>{const s=state.sessions.find(s=>s.waiting);if(!s)return;state.session=s.id;state.shell=s.shells[0]?.id;state.page='workspace';render();},
  'end-session':b=>{const s=state.sessions.find(s=>s.id===b.dataset.id)||current();if(!s)return;openDialog('结束会话？',`<p class="note">结束「${escapeHtml(s.name)}」会关闭该连接的全部 ${s.shells.length} 个 Shell 及关联转发。历史输出保留。</p>`,button('取消','close-dialog')+button('结束并归档','confirm-end','danger','data-id="'+s.id+'"'));},
  'confirm-end':b=>{const s=state.sessions.find(s=>s.id===b.dataset.id);if(!s)return;state.history.unshift({id:'h-'+s.id,name:s.name,connection:s.connection,time:'刚刚',tag:'',reason:'手动结束'});state.sessions=state.sessions.filter(x=>x.id!==s.id);state.rules=state.rules.filter(r=>r.session!==s.name);state.forwards=state.forwards.filter(f=>f.session!==s.id);if(state.session===s.id){state.session=state.sessions[0]?.id;state.shell=state.sessions[0]?.shells[0]?.id;state.input=false;}closeDialog();render();toast('会话已结束，输出保留（模拟）');},
  'new-shell':()=>{if(!available()||!current()){toast('请先打开运行中的会话');return;}openDialog('新建 Shell','<form id="shell-form"><label class="field">名称 / 命令<input name="name" value="bash" maxlength="60" required></label><p class="note">Shell 共享当前会话的连接，与其他 Shell 同级。</p></form>',button('取消','close-dialog')+button('创建 Shell','create-shell','primary'));},
  'create-shell':()=>{if(!$('#shell-form').reportValidity())return;const name=new FormData($('#shell-form')).get('name').trim();const id='sh-demo-'+Date.now();current().shells.push({id,name,exited:false});state.shell=id;state.input=false;state.terminalMinimized=false;closeDialog();render();toast('Shell 已创建（模拟）');},
  'enable-input':()=>{state.input=true;state.terminalMinimized=false;render();$('#terminal-command')?.focus();},'disable-input':()=>{state.input=false;render();},
  'interrupt':()=>{state.output[state.shell]=(state.output[state.shell]||'')+'\n<span class="yellow">^C</span>\n<span class="dim">已发送中断键（模拟）；不阻止后续 MCP 输入。</span>';current().waiting=false;render();toast('已发送 Ctrl+C（模拟）');},
  'close-shell':()=>openDialog('关闭当前 Shell？','<p class="note">仅关闭当前 Shell，其他 Shell 保持运行。手动关闭会移除该 Shell；PTY 会话可继续新建 Shell。</p>',button('取消','close-dialog')+button('关闭 Shell','confirm-close-shell','danger')),
  'confirm-close-shell':()=>{const s=current();s.shells=s.shells.filter(sh=>sh.id!==state.shell);state.shell=s.shells[0]?.id;state.input=false;closeDialog();render();toast('Shell 已关闭（模拟）');},
  'copy-session':()=>copy('termcp://#'+state.session),'copy-shell':()=>copy('termcp://#'+state.session+':'+(current().shells.findIndex(sh=>sh.id===state.shell)+1)),'copy-mcp':()=>copy(mcpConfig()),'copy-example':()=>copy('termcp://#s-demo-01'),
  'new-folder':()=>openDialog('新建目录','<form id="folder-form"><label class="field">目录名称<input name="name" placeholder="assets" required maxlength="80" pattern="[^/]+"></label></form>',button('取消','close-dialog')+button('创建目录','create-folder','primary')),
  'create-folder':()=>{if(!$('#folder-form').reportValidity())return;const name=new FormData($('#folder-form')).get('name').trim();state.files.push({session:state.session,name:name+'/',type:'目录',size:'—'});closeDialog();render();toast('目录已创建（模拟）');},
  'upload-file':()=>{state.files.push({session:state.session,name:'demo-'+(state.files.length+1)+'.txt',type:'文件',size:'256 B'});render();toast('演示文件已添加；正式版使用 SFTP 上传');},
  'file-preview':b=>{const f=currentFiles()[Number(b.dataset.id)];openDialog(escapeHtml(f.name),f.type==='目录'?'<div class="empty">演示目录为空。</div>':'<pre class="config-code">Demo file content\n\nThis is a prototype preview.</pre>');},
  'add-forward':()=>openDialog('添加端口转发','<form id="forward-form"><label class="field">类型<select name="kind"><option value="Local · -L">Local · -L</option><option value="Remote · -R">Remote · -R</option><option value="Dynamic · -D">Dynamic · -D（SOCKS）</option></select></label><label class="field">监听地址<input name="source" value="127.0.0.1:8080" required></label><label class="field" id="forward-target">目标地址<input name="target" value="127.0.0.1:80" required></label><div id="forward-error" class="error-text" role="alert"></div></form>',button('取消','close-dialog')+button('创建转发','create-forward','primary')),
  'create-forward':()=>{const f=$('#forward-form');if(!f.reportValidity())return;const d=new FormData(f);const address=/^[a-zA-Z0-9.\-]+:(\d{1,5})$/;const valid=v=>address.test(v)&&Number(v.match(address)[1])>0&&Number(v.match(address)[1])<=65535;if(!valid(d.get('source'))||(d.get('kind')!=='Dynamic · -D'&&!valid(d.get('target')))){$('#forward-error').textContent='请输入有效的 host:port 地址（端口 1–65535）。';return;}state.forwards.push({session:state.session,id:'f-demo-'+Date.now(),kind:d.get('kind'),source:d.get('source'),target:d.get('kind')==='Dynamic · -D'?'SOCKS proxy':d.get('target')});closeDialog();render();toast('端口转发已创建（模拟）');},
  'delete-forward':b=>{state.forwards=state.forwards.filter(f=>f.id!==b.dataset.id);render();toast('转发已关闭（模拟）');},
  'remove-rule':b=>{state.rules=state.rules.filter(r=>r.id!==b.dataset.id);render();toast('通知规则已移除（模拟）');},
  'connection-detail':b=>connectionDetail(b.dataset.id),
  'test-connection':()=>toast('模拟测试通过 · SSH 连接可用'),
  'new-connection':()=>openDialog('新建 SSH 配置','<form id="connection-form"><label class="field">配置名称<input name="name" placeholder="my-server" pattern="[A-Za-z0-9_-]+" required></label><label class="field">主机<input name="host" placeholder="server.example.test" required></label><label class="field">用户<input name="user" placeholder="developer" required></label><label class="field">认证方式<select name="auth"><option>密码</option><option>私钥 PEM 内容</option></select></label><label class="field">凭据<textarea name="credential" placeholder="仅演示，不会保存任何凭据" aria-label="演示凭据"></textarea><small>正式版凭据仅写入 core，不读回。</small></label><div id="profile-error" class="error-text" role="alert"></div></form>',button('取消','close-dialog')+button('保存配置','create-connection','primary')),
  'create-connection':()=>{const f=$('#connection-form');if(!f.reportValidity())return;const d=new FormData(f);if(state.connections.some(c=>c.name===d.get('name'))){$('#profile-error').textContent='配置名称已存在。';return;}state.connections.push({name:d.get('name'),host:d.get('host').trim(),user:d.get('user').trim(),kind:'remote'});closeDialog();render();toast('连接配置已添加（模拟）；凭据未保存');},
  'history-preview':b=>{const h=state.history.find(h=>h.id===b.dataset.id);if(!h)return;openDialog(escapeHtml(h.name)+' · 历史输出',`${badge('只读归档','neutral')}<p class="note">${escapeHtml(h.connection)} · ${escapeHtml(h.reason)}</p><pre class="history-preview">$ npm run build\n\n✓ Type check completed\n✓ Build completed\n\n[Session ended · demo transcript]</pre><p class="note">正式版按字节 offset 分页读取真实输出。</p>`,button('关闭','close-dialog')+button('新建同配置会话','session-from-connection','primary','data-id="'+escapeHtml(h.connection)+'"'));},
  'history-edit':b=>{const h=state.history.find(h=>h.id===b.dataset.id);openDialog('编辑历史信息',`<form id="history-form"><label class="field">名称<input name="name" value="${escapeHtml(h.name)}" required></label><label class="field">标签<input name="tag" value="${escapeHtml(h.tag)}"></label></form>`,button('取消','close-dialog')+button('保存','save-history','primary','data-id="'+h.id+'"'));},
  'save-history':b=>{const f=$('#history-form');if(!f.reportValidity())return;const d=new FormData(f);const h=state.history.find(h=>h.id===b.dataset.id);h.name=d.get('name').trim();h.tag=d.get('tag').trim();closeDialog();render();toast('历史信息已更新（模拟）');},
  'history-delete':b=>openDialog('永久删除历史？','<p class="note">将清理这条归档会话的输出与消息。此动作与结束运行中的会话不同。</p>',button('取消','close-dialog')+button('删除历史','confirm-history-delete','danger','data-id="'+b.dataset.id+'"')),
  'confirm-history-delete':b=>{state.history=state.history.filter(h=>h.id!==b.dataset.id);closeDialog();render();toast('历史已删除（模拟）');},
  'save-settings':()=>{const form=$('#settings-form');if(!form.reportValidity())return;const d=new FormData(form);const host=d.get('host').trim();if(!['127.0.0.1','localhost','::1'].includes(host)&&!d.get('token')){$('#settings-error').textContent='监听非 loopback 地址必须配置认证 Token。';return;}openDialog('应用设置并重启？',`<p class="note">设置将保存，当前 ${state.sessions.length} 个会话会断开并归档。演示 Token 不会保存。停止中的 core 会以新参数启动。</p>`,button('取消','close-dialog')+button('应用并重启','confirm-settings','primary'));},
  'confirm-settings':()=>{const d=new FormData($('#settings-form'));state.config={host:d.get('host').trim(),port:d.get('port'),dataDir:d.get('dataDir').trim(),log:d.get('log'),internal:d.has('internal'),manage:d.has('manage')};archiveSessions('应用设置重启');state.connections=state.connections.filter(c=>c.kind!=='internal');if(state.config.internal)state.connections.unshift({name:'internal',host:'termcp 所在本机',kind:'internal',user:'—',group:'本机',port:22,favorite:false});state.running=true;event('运行设置已应用','Core 重启 · 演示');closeDialog();state.page='core';render();toast('设置已应用并重启（模拟）');}
};
document.addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b||b.disabled)return;
  const pane=b.closest('[data-pane]');if(pane)focusPane(pane.dataset.pane);
  if(b.dataset.concept){state.concept=b.dataset.concept;state.page=concepts[state.concept].page;state.input=false;render();return;}
  if(b.dataset.page){navigate(b.dataset.page);return;}
  if(b.dataset.shell){const session=state.sessions.find(s=>s.shells.some(sh=>sh.id===b.dataset.shell));if(session)openSessionView(session,b.dataset.shell);render();return;}
  if(b.dataset.tool){state.tool=b.dataset.tool;render();return;}
  if(b.dataset.action&&actions[b.dataset.action])actions[b.dataset.action](b);
});
document.addEventListener('input',e=>{if(e.target.dataset.filter==='sessions'){state.query=e.target.value;$('#session-results').innerHTML=sessionResults();}if(e.target.dataset.filter==='history'){state.historyQuery=e.target.value;$('#history-results').innerHTML=historyResults();}});
document.addEventListener('change',e=>{if(e.target.closest('#forward-form')&&e.target.name==='kind'){const dynamic=e.target.value==='Dynamic · -D';$('#forward-target').hidden=dynamic;$('#forward-target input').required=!dynamic;}});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id!=='terminal-form'||!state.input)return;const input=$('#terminal-command');const text=input.value.trim();if(!text)return;const s=current();s.waiting=false;state.output[state.shell]=(state.output[state.shell]||'')+`\n<span class="green">❯ ${escapeHtml(text)}</span>\n<span class="dim">[模拟输入已发送，未执行真实命令]</span>`;if(text==='exit'){s.shells.find(sh=>sh.id===state.shell).exited=true;state.input=false;}render();$('#terminal-command')?.focus();});
Object.assign(actions,workspaceActions);
setupWorkspaceInteractions();
render();
