// Monitoring is a design sample. Core currently has no telemetry endpoint.
const demoTelemetry = {
  'dev-server':{os:'Ubuntu 24.04 LTS',arch:'x86_64',uptime:'4 天 06:21',cpu:18.5,cores:[12,24,22,16],memory:38,used:'3.0',total:'8.0',cached:'1.2',upload:'12.4',download:'84.6',disk:42,diskUsed:'42.0',diskTotal:'100',mount:'/',fs:'ext4',read:'32',write:'8',trend:[12,15,10,17,23,21,18,26,20,18,17,19]},
  staging:{os:'Debian 12',arch:'x86_64',uptime:'12 天 14:08',cpu:32,cores:[38,27,31,32],memory:61,used:'9.8',total:'16.0',cached:'2.1',upload:'46.2',download:'128.0',disk:57,diskUsed:'114',diskTotal:'200',mount:'/',fs:'ext4',read:'64',write:'24',trend:[24,28,25,33,30,38,35,29,37,31,34,32]},
  internal:{os:'本机系统 · 示例',arch:'arm64',uptime:'2 天 03:12',cpu:9,cores:[8,12,6,10],memory:27,used:'4.3',total:'16.0',cached:'1.1',upload:'2.1',download:'16.8',disk:34,diskUsed:'170',diskTotal:'500',mount:'/',fs:'APFS',read:'16',write:'4',trend:[4,6,5,8,6,10,7,12,10,8,11,9]}
};
function telemetryFor(s){return demoTelemetry[s.connection]||null;}
function sparkline(values,cls=''){
  const points=values.map((v,i)=>`${i*200/(values.length-1)},${42-v*.5}`).join(' ');
  return `<svg class="metric-chart ${cls}" viewBox="0 0 200 48" preserveAspectRatio="none" aria-hidden="true"><path class="chart-grid" d="M0 12H200M0 28H200M0 44H200"/><polygon class="chart-fill" points="0,48 ${points} 200,48"/><polyline class="chart-line" points="${points}"/></svg>`;
}
function hostInspector(s,sh){
  const m=telemetryFor(s),profile=state.connections.find(c=>c.name===s.connection);
  if(state.inspectorCollapsed)return `<aside class="host-inspector host-inspector-rail" aria-label="主机状态工具条">${iconButton('展开主机详情','toggle-inspector','panel','aria-expanded="false"')}<div class="rail-metrics" title="示例监控快照"><span>CPU<b>${m?m.cpu+'%':'—'}</b></span><span>内存<b>${m?m.used+'G':'—'}</b></span><span>磁盘<b>${m?m.disk+'%':'—'}</b></span></div>${iconButton('管理当前会话','manage-session','settings')}${iconButton('复制 Shell 资源 URL','copy-shell','copy',!sh?'disabled':'')}<small>示例</small></aside>`;
  const status=sh?.exited?'Shell 已退出':s.waiting?'需人工输入':'已连接';
  return `<aside class="host-inspector" aria-label="主机详情"><header class="host-inspector-header"><span>主机详情</span><div class="window-controls">${iconButton('管理当前会话','manage-session','settings')}${iconButton('收起主机详情','toggle-inspector','panel','aria-expanded="true"')}</div></header><div class="inspector-host"><span class="dot ${sh?.exited?'gray':s.waiting?'amber':''}"></span><strong>${escapeHtml(s.connection)}</strong><span class="inspector-host-state">${status}</span><small>${escapeHtml(s.kind==='internal'?'Core 所在本机':(profile?.user||'SSH')+'@'+s.host)}</small></div><nav class="inspector-tabs" aria-label="主机详情视图">${[['monitor','监控'],['session','termcp']].map(([key,label])=>`<button data-action="inspector-tab" data-id="${key}" aria-pressed="${state.inspectorTab===key}">${label}</button>`).join('')}</nav><div class="inspector-body">${state.inspectorTab==='session'?sessionInspection(s,sh,profile):monitorInspection(m)}</div><footer class="inspector-foot"><span>${state.inspectorTab==='session'?'跟随当前窗格':'示例监控 · 未连接采集器'}</span><span>${sh?escapeHtml(sh.name):'—'}</span></footer></aside>`;
}
function monitorInspection(m){
  if(!m)return '<div class="monitor-unavailable"><span>◌</span><b>尚未采集主机状态</b><p>当前主机没有监控快照。正式版需通过 termcp 的独立监控通道采集。</p></div>';
  return `<section class="monitor-system"><div class="monitor-heading"><span>系统</span><small>${m.arch}</small></div><strong>${m.os}</strong><div class="system-time"><span>运行时间</span><b>${m.uptime}</b></div></section><section class="monitor-section"><div class="monitor-heading"><span>CPU</span><strong>${m.cpu}<small>%</small></strong></div>${sparkline(m.trend)}<div class="core-bars">${m.cores.map((value,i)=>`<div><span>${i+1}</span><div class="core-track"><i style="width:${value}%"></i></div><b>${value.toFixed(1)}%</b></div>`).join('')}</div></section><section class="monitor-section"><div class="monitor-heading"><span>内存</span><small>${m.total} GB</small></div><div class="memory-overview"><div class="memory-ring" style="--usage:${m.memory}%"><span>${m.memory}<small>%</small></span></div><dl><div><dt><i class="legend-used"></i>已用</dt><dd>${m.used} GB</dd></div><div><dt><i class="legend-cached"></i>缓存</dt><dd>${m.cached} GB</dd></div><div><dt>可用</dt><dd>${(Number(m.total)-Number(m.used)).toFixed(1)} GB</dd></div></dl></div></section><section class="monitor-section"><div class="monitor-heading"><span>网络</span><small>eth0 · 示例</small></div>${sparkline(m.trend.map(v=>v*1.5),'network-chart')}<div class="network-values"><span><small>↑ 上传</small><b>${m.upload}<em> KB/s</em></b></span><span><small>↓ 下载</small><b>${m.download}<em> KB/s</em></b></span></div></section><section class="monitor-section monitor-disk"><div class="monitor-heading"><span>磁盘</span><small>${m.fs}</small></div><div class="disk-label"><span>${m.mount}</span><b>${m.diskUsed} / ${m.diskTotal} GB</b></div><div class="disk-track"><i style="width:${m.disk}%"></i></div><div class="disk-rates"><span>读 ${m.read} KB/s</span><span>写 ${m.write} KB/s</span></div></section>`;
}
function sessionInspection(s,sh,profile){
  const resource='termcp://#'+s.id;
  const shellResource=sh?resource+':'+(s.shells.findIndex(x=>x.id===sh.id)+1):'';
  return `<section class="monitor-section session-properties"><div class="monitor-heading"><span>连接</span><small>${s.kind==='internal'?'LOCAL':'SSH / PTY'}</small></div><dl><div><dt>会话</dt><dd>${escapeHtml(s.name)}</dd></div><div><dt>地址</dt><dd>${escapeHtml(s.host)}${s.kind==='remote'?':'+(profile?.port||22):''}</dd></div><div><dt>跳板</dt><dd>${escapeHtml(profile?.jump||'直接连接')}</dd></div><div><dt>Core</dt><dd>Local core :${escapeHtml(state.config.port)}</dd></div><div><dt>输入</dt><dd>${state.input?'本地输入开启':'观察模式'}</dd></div></dl></section><section class="monitor-section"><div class="monitor-heading"><span>Shells</span>${iconButton('在当前连接新建 Shell','new-shell','add')}</div><div class="inspector-shells">${s.shells.map(x=>`<button data-action="inspect-shell" data-id="${x.id}" aria-pressed="${x.id===sh?.id}"><span class="dot ${x.exited?'gray':''}"></span><span>${escapeHtml(x.name)}</span><small>${x.exited?'只读':'运行中'}</small></button>`).join('')}</div></section><section class="monitor-section"><div class="monitor-heading"><span>共享给 Agent</span><small>MCP</small></div><div class="resource-copy"><span>会话</span>${iconButton('复制会话资源 URL','copy-session','copy')}<code>${escapeHtml(resource)}</code></div>${sh?`<div class="resource-copy"><span>当前 Shell</span>${iconButton('复制 Shell 资源 URL','copy-shell','copy')}<code>${escapeHtml(shellResource)}</code></div>`:''}<p class="sharing-note">GUI 和 MCP 共享会话输入。</p></section>`;
}
